[cache]
top_dir = "CacheStorage"
root = "defaultCache"
#model_filename = "model_rwkv_gutenberg"
#main_filename = "rwkv_test004"
#pd_filename = "rwkv_pd_test001"
# pd_filename = "rwkv_pd_test002"

# モデルを変えてみる実験用 2024/03/12 19:04
#main_filename = "rwkv-4-world-7b-test01"
#pd_filename = "rwkv-4-world-7b-pd-test01"

# キャッシュが壊れた気がするのでやり直してみる 2024/03/14 18:42
model_filename = "rwkv-4-world-7b-model-test04"
main_filename = "rwkv-4-world-7b-test04"
pd_filename = "rwkv-4-world-7b-pd-test04"



[io]
input_filename_original = "embedding-data.parquet" # original
input_filename_finetuned = "ft-embedding-data.parquet" # finetuned
original_model = "sentence-transformers/all-MiniLM-L6-v2"
finetuned_model = "models/mpnet-base-all-nli-triplet/final"


