# global configuration
hydra:
    run:
#        dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M}
        dir: ./outputs/tese
    job:
        chdir: True

cache:
    top_dir: "CacheStorage"
    root: "defaultCache"
    pd:
        prefix: "PersistenceDiagram"
        filename: "pd_test01"
